backend:
  name: git-gateway
  branch: main
media_folder: "public/img/blog"
public_folder: "/img/blog"
collections:
  - name: "config"
    label: "Site price Informations"
    files:
      - file: "src/config/price.md"
        label: "Price Informations"
        name: "price"
        fields:
          - { label: "Kids Plan-Moment", name: "kidsMoment", widget: "string" }
          - { label: "Kids Plan-Dream", name: "kidsDream", widget: "string" }
          - { label: "Kids Plan-Eternalize", name: "kidsEtenalize", widget: "string" }
          - { label: "Maternity-Moment", name: "maternityMoment", widget: "string" }
          - { label: "Maternity-Drem", name: "maternityDrem", widget: "string" }
          - { label: "Maternity-Sweet", name: "maternitySweet", widget: "string" }
          - { label: "Family-Moment", name: "familyMoment", widget: "string" }
          - { label: "Family-Drem", name: "familyDrem", widget: "string" }
          - { label: "Family-Tales", name: "familyTales", widget: "string" }
          - { label: "Birthday-Moment", name: "birthdayMoment", widget: "string" }
          - { label: "Birthday-Drem", name: "birthdayDrem", widget: "string" }
          - { label: "Birthday-Etenalize", name: "birthdayEtenalize", widget: "string" }
          - { label: "Adulthood-Moment", name: "adulthoodMoment", widget: "string" }
          - { label: "Adulthood-Drem", name: "adulthoodDrem", widget: "string" }
          - { label: "Adulthood-Etenalize", name: "adulthoodEtenalize", widget: "string" }
        