backend:
  name: github
  repo: marcelocho/orita-teste
  branch: main
  base_url: https://orita-teste.vercel.app
  auth_endpoint: /api/auth
  auth_scope: "repo" # Corrigido como fizemos antes

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "test"
    label: "Post de Teste"
    folder: "src/test"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }