backend:
  name: github
  repo: marcelocho/orita-teste  # troque pelo seu repositório GitHub
  branch: main
  base_url: https://orita-teste.vercel.app
  auth_endpoint: /api/auth

media_folder: "public/uploads" # onde os arquivos serão salvos no repo
public_folder: "/uploads"      # caminho público dos arquivos no site

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
